sign-prefix:
  # What the user needs to type to create a sign marker
  user-input: "[BSM]"
  # What the sign should display when the user finishes the sign
  output: "&7[&bBSM&7]"
  # Change this to the old value of "output" when changing "output".
  # This way, all signs will be updated to the new value.
  migration: "&7[&bBSM&7]"
# What the chat messages should be prefixed with
message-prefix: "&7[&bBSM&7] &r"
# How the user should be notified that the sign was created
# Use "ACTIONBAR" for the action bar, "CHAT" for the chat, or "NONE" for nothing
message-type: "ACTIONBAR"